### ISSUE TITLE
How can I change the centering

### ISSUE THREAD

**Issue by zoebjamal** [cotemaxime/obsidian-purple-theme#6]
Hi, I love this theme but I would like to change the centering of the text. For example, in the first screenshot, the text goes all the way to the ends of the entry window but when using amethyst, it does not stretch all the way to the edges. I have already removed the color bars that fill the edges but I was wondering if there was any way to make the text stretch all the way to the edges. 

Thank you!
![Screen Shot 2021-05-01 at 5 54 22 PM](https://user-images.githubusercontent.com/62960617/116782390-6e7e5c00-aaa6-11eb-823b-2f78a2af95dd.png)
![Screen Shot 2021-05-01 at 5 54 36 PM](https://user-images.githubusercontent.com/62960617/116782392-6faf8900-aaa6-11eb-8352-5e08da240d92.png)

**Comment by cotemaxime** [comment]
Normally the only place where I change the width is at the very bottom with the border padding 

![image](https://user-images.githubusercontent.com/6462468/116799101-ffaffb80-aac3-11eb-8d08-eadaa70d15a3.png)

Normally commenting those should fix it, unless that's what you already did in which case could it be the "readable lenght" option in Obsidian? Since that has the same effect without the purple

**Comment by zoebjamal** [comment]
Updating the readable file length helped thank you so much!
